### ISSUE TITLE
Future plan for gsDesign2 and simtrial

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsDesign2#288]
**Functionality:**
- [x] `simtrial::sim_gs()`: simulate time-to-event endpoints in group sequential designs with given sample size. @LittleBeannie 
- [x] `simtrial::get_analysis_date()`: get the analysis date decided by multiple conditions: (1) calendar time, (2) targeted event, (3) max time extension to reach targeted events, (4) planned minimum time after the previous analysis, (5) minimal follow-up time after specified enrollment fraction. @LittleBeannie 
  (see https://github.com/Merck/simtrial/issues/116)
- [x] `simtrial::early_zero_weight()`: a weighting function which has zero/non-zero weights at the early/late phase.@LittleBeannie
  (see https://github.com/Merck/simtrial/issues/123).
- [x] `simtrial::milestone()`: milestone test (see https://github.com/Merck/simtrial/issues/197) @LittleBeannie
- [x] `simtrial::rmst()`: RMST test (see https://github.com/Merck/simtrial/issues/16) @LittleBeannie 
- [x] Revert back `create_arm()` workaround after bug fix in upstream (see #346 ) @LittleBeannie 
- [x] Zero failure rates (see #360) @LittleBeannie 
- [x] Implement parallel adaptor in `sim_gs_n()` (see https://github.com/Merck/simtrial/issues/205) @cmansch
- [ ] `gsDesign2::gs_conditional_power()`: conditional power. @shiyuskaya, @LittleBeannie
- [ ] `gsDesign2::gs_design_wlr()` and `gs_power_wlr()`: add stratified designs. @elong0527 
  (see #129)
- [ ] gsDesign2: text summary

**Shiny app:**
- [ ] gsDesign2 by Greg Chen
- [ ] simtrial

**Documentation:**
- [x] gsDesign2: updated boundary (see #331) @LittleBeannie 
- [x] Vignette of the information under the null and alternative hypothesis (see #289) @LittleBeannie
- [x] Update spending bound vignette (see #290) @keaven

**Code practice:**
- [x] Reasonable `as_gt()` code example output (see #334) @nanxstats 
- [ ] Tidy up `summary` and `as_gt` functions (see #282) @jdblischak 
- [ ] Remove `npsurvSS` dependency (see #257) @elong0527 
- [x] Refactor `sim_gs_n()` to improve interface and performance (see https://github.com/Merck/simtrial/issues/196) @jdblischak 
- [x] Refactor `do.call(rbind)` with `data.table::rbindlist()` in RMST (see https://github.com/Merck/simtrial/issues/193) @jdblischak 
- [x] Create formula interface for RMST test (see https://github.com/Merck/simtrial/issues/189) @jdblischak 
- [ ] Remove the seed argument from `sim_gs_n()` @jdblischak 

**Numerical performance:**
- [ ] Accelerate numerical integration with OpenMP (see #321) @nanxstats 
- [ ] Benchmark Python table backends in simrial (see https://github.com/Merck/simtrial/issues/183) @nanxstats 

**Release:**
- [x] First CRAN release of simtrial around Dec, 2023
- [x] gsDesign2 1.1.1 CRAN release @nanxstats

**Comment by LittleBeannie** [comment]
I will close this issue since the above items are available as individual issues in gsDesign2 GitHub repo.
