### ISSUE TITLE
Todo list before upcoming release

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsDesign2#73]
## Bugs

- [x] Non-binding design of max combo design (issue #71)
- [x] `gs_design_combo` with fixed boundary (issue #62)
- [x] Remove warning message from `gs_design_combo` and `gs_power_combo` (issue #74 )
- [x] Fix boundary calculation under H0 with spending bound (issue #80)

## Documents
- [x] Add footnotes of type I error of non-binding design (issue #72)
- [x] Add more text to use cases vignettes (issue #69)
- [x] Remove the `simtrial` dependency (issue #52)
- [x] Re-organize vignettes (issue #75, issue #85)
- [x] Remove `ahr_binded` (issue #86)
- [x] Update README (issue #89 )
- [x] Detail the documentation of `r` like gsDesign (issue #97)

## New features
- [x] Add parameter to wMB (issue #78)

## Tests
- [x] RD tests (issue #34)
- [x] WLR test (issue #32, issue #94)
- [x] Maxcombo test (issue #82, issue #68,  also depends on issue #71)
- [x] AHR test (issue #31)
- [x] RMST test (issue #35)

## Grammar
- [x] style guide (issue #84, #101)

**Comment by nanxstats** [comment]
@LittleBeannie maybe we can close this?

**Comment by LittleBeannie** [comment]
> @LittleBeannie maybe we can close this?

Let's wait until this Friday and check with Keaven if he is okay with a GitHub release next week. After his approval, we can close this issue.
